# Use the official Redis image
FROM redis:latest

# If you need to copy a custom redis.conf file:
# COPY redis.conf /usr/local/etc/redis/redis.conf

# Expose default port 6379
EXPOSE 6379

# If you want to set up a persistent data directory:
# VOLUME /data


# Default command to start Redis.  Can be overridden when running the container.